[project]
name = 'Decentralized-Cross-Industry-Innovation-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.commercialization-tracking]
path = 'contracts/commercialization-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.industry-matching]
path = 'contracts/industry-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.innovation-registration]
path = 'contracts/innovation-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.innovator-verification]
path = 'contracts/innovator-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
